#!/bin/bash
declare USAGE="checktest <number (0~19)> [-n]"
declare PR=$(basename $(pwd))

if [ $# -lt 1 ]; then
  echo $USAGE
  exit 1
fi

inpath="dataset_$PR/input/input$1.txt"

if [ ! -e $inpath ]; then
  echo "$inpath is non-existing" >&2
  exit 2
fi

if [ ! -e "$PR.cpp" ]; then
  echo "no executable" >&2
  exit 2
fi

##

if diff "output.txt" "dataset_$PR/output/output$1.txt";
  then
    echo "good";
  else
    echo "bad";
    case $2 in
      -n | n)
        ;;
      *) p4merge "output.txt" "dataset_$PR/output/output$1.txt"
        ;;
    esac
fi