#!/bin/bash
declare USAGE="testone <number> [-n]"
declare PR=$(basename $(pwd))

if [ $# -lt 1 ]; then
  echo $USAGE
  exit 1
fi

inpath="dataset_$PR/input/input$1.txt"

if [ ! -e $inpath ]; then
  echo "$inpath is non-existing" >&2
  exit 2
fi

if [ ! -e "$PR.cpp" ]; then
  echo "no executable" >&2
  exit 2
fi

##

cp $inpath "input.txt";
# crunt "$PR.cpp";
crunj

# head -n1 "output.txt" > "output1.txt";

  awk 	'BEGIN { RS="\\*\\*\\*\\n"; ORS="***\n" }
	{ last = $0 }
	END { print last }
	' "output.txt" > "dataset_$PR/my_output/myoutput$1.txt"
	
  gradeone $1;	


# if diff "output.txt" "dataset_$PR/output/output$1.txt";
#  then
#    echo "================"
#    echo "correct output :)";
#    echo "================"
#  else
#    echo "================"
#    echo "wrong output :(";
#    echo "================"
#    case $2 in
#      -n | n)
#        ;;
#      *) p4merge "output.txt" "dataset_$PR/output/output$1.txt"
#        ;;
#    esac
# fi
