#!/bin/bash
declare USAGE="testall [-n]"
declare PR=$(basename $(pwd))

if [ ! -e "dataset_$PR/input/input0.txt" ]; then
  echo "no dataset" >&2
  exit 2
fi

if [ ! -e "$PR.cpp" ]; then
  echo "no executable" >&2
  exit 2
fi

##

declare -a index=(
  0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
);
declare ngood=0;
declare nbad=0;

for i in "${index[@]}"; do
  cp "dataset_$PR/input/input$i.txt" "input.txt";
  # crunt "$PR.cpp";
  crunj

  # head -n1 "output.txt" > "output1.txt";

  if diff "output.txt" "dataset_$PR/output/output$i.txt";
    then
      echo "----------------"
      echo "$i +";
      echo "----------------"
      ngood=$((ngood+1));
    else
      echo "$i x";
      nbad=$((nbad+1));
      case $1 in
        -n | n)
          ;;
        *) p4merge "output.txt" "dataset_$PR/output/output$i.txt"
          ;;
      esac
  fi
done
  echo "================"
  echo "$ngood/$((ngood+nbad))"
  echo "================"
