#!/bin/bash
declare USAGE="viewplt <-d <number> | -r <number>>"
declare PR=$(basename $(pwd))


pltpath=""

## parsing

case $# in
  2 )
  ;;
  *)
    echo $USAGE 
    exit 1
  ;;
esac

case $1 in
  -d | -dataset | d | dataset)
  pltpath="dataset_$PR/plt/plt$2.png"
  ;;
  -r | -randset | r | randset)
  pltpath="randset_$PR/plt/rplt$2.png"
  ;;
  *)
  echo $USAGE
  exit 3
  ;;
esac


if [ ! -e $pltpath ]; then
  echo "$pltpath is non-existing" >&2
  exit 4
fi

## 

code $pltpath